package utils

const (
	GOODNOTES_STANDARD_FLASHCARD_WIDTH  = 455.04
	GOODNOTES_STANDARD_FLASHCARD_HEIGHT = 588.45

	A4_PAGE_WIDTH  = 595.28
	A4_PAGE_HEIGHT = 841.89

	DIMENSION_TOLERANCE = 2.0

	QuestionKeyword = "QUESTION"
	AnswerKeyword   = "ANSWER"
)
