name: Build Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'content/**'    # Triggered when content is updated from main repo
      - '_templates/**' # Or when templates are updated
      - 'scripts/**'    # Or when generation script is updated

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run build:docs

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: rebuild documentation"
          git push